/**
 * Request context middleware.
 *
 * Generates a unique request ID for every incoming request, attaches it to
 * the request object, and includes it in the response header `X-Request-Id`.
 */

import type { FastifyInstance } from "fastify";
import fp from "fastify-plugin";

declare module "fastify" {
  interface FastifyRequest {
    /**
     * Unique identifier for this request.
     * Generated by requestContextPlugin if not already present in headers.
     */
    requestId: string;
  }
}

async function registerRequestContextPlugin(
  app: FastifyInstance
): Promise<void> {
  app.addHook("onRequest", async (request, reply) => {
    // Honour incoming X-Request-Id if provided (e.g. from a proxy or test harness)
    const incoming =
      request.headers["x-request-id"] ??
      request.headers["X-Request-Id"];

    const id =
      typeof incoming === "string" && incoming.length > 0
        ? incoming
        : crypto.randomUUID();

    request.requestId = id;
    void reply.header("X-Request-Id", id);
  });
}

export const requestContextPlugin = fp(registerRequestContextPlugin, {
  name: "request-context-plugin",
  fastify: "5.x",
});
